"""Initial_migration

Revision ID: 94f9bd94acf9
Revises: 897804e0eb80
Create Date: 2025-10-28 17:12:37.580296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f9bd94acf9'
down_revision = '897804e0eb80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###