apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "employee-productivity-api.fullname" . }}-models
  labels:
    {{- include "employee-productivity-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
